version: '3.7'

services:
  notebook:
    image: jupyter/all-spark-notebook
    container_name: notebook
    networks:
      spark-cluster:
    ports:
      - '8888:8888'
      - '4040:4040'
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages com.amazonaws:aws-java-sdk-bundle:1.11.819,org.apache.hadoop:hadoop-aws:3.2.0 pyspark-shell
